version: '3.5'

services:

  splunk:

    container_name: splunk
    hostname: splunk
    build: splunk
    environment:
      - SPLUNK_PASSWORD=roach1234
      - SPLUNK_START_ARGS=--accept-license
      - DEBUG=true
    volumes:
      - /Users/timveil/dev/troubleshooting/logs:/tmp/cockroach-batch
    ports:
      - "8000:8000"

