version: '3.5'

volumes:
  opt-splunk-var:
  opt-splunk-etc:

services:

  splunk:
    container_name: splunk
    hostname: splunk
    build: splunk
    environment:
      - SPLUNK_PASSWORD=roach1234
      - SPLUNK_START_ARGS=--accept-license
      - DEBUG=true
    volumes:
      - opt-splunk-var:/opt/splunk/var
      - opt-splunk-etc:/opt/splunk/etc
    ports:
      - "8000:8000"

