version: '3.5'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:

  splunk:

    container_name: splunk
    hostname: splunk
    build: splunk
    environment:
      - SPLUNK_PASSWORD=roach1234
      - SPLUNK_START_ARGS=--accept-license
      - DEBUG=true
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var      -
      - ${LOCAL_LOG_DIR}:/tmp/cockroach-batch
    ports:
      - "8000:8000"

